FROM nginx:1.19.1

COPY ls-nginx/nginx.conf /etc/nginx/nginx.conf

COPY ls-nginx/key-selfsigned/selfsigned.key /etc/ssl/private/nginx-selfsigned.key
COPY ls-nginx/key-selfsigned/selfsigned.crt /etc/ssl/certs/nginx-selfsigned.crt
COPY ls-nginx/key-selfsigned/dhparam.pem /etc/ssl/certs/dhparam.pem

COPY ls-nginx/snippets/ssl-params.conf /etc/nginx/snippets/ssl-params.conf
COPY ls-nginx/snippets/self-signed.conf /etc/nginx/snippets/self-signed.conf
