version: '3.8'
services:
  nginx:
    container_name: nginx-ls
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/nginx-v/log:/var/log/nginx
    depends_on:
      - lightsearch-server
    expose:
      - 80
      - 443
    restart: always
  lightsearch-server:
    container_name: lightsearch-server
    build:
      context: .
      dockerfile: Dockerfile-lightsearch
    volumes:
      - ${PWD}/lightsearch-v/logs:/logs
      - type: bind
        source: ${PWD}/lightsearch-v/blacklist
        target: /blacklist
    expose:
      - 50000
